#!/bin/sh
thisdir="`cd "$(dirname "$0")"; pwd`"
cc="clang"
libc="`readlink -f "$thisdir/../build/sysroot"`"
libc_inc="$libc/include"
libc_lib="$libc/lib"

# prevent clang from running the linker (and erroring) on no input.
sflags=
eflags=
for x ; do
    case "$x" in
        -l*) input=1 ;;
        *) input= ;;
    esac
    if test "$input" ; then
        sflags="-l-user-start"
        eflags="-l-user-end"
        break
    fi
done

exec $cc \
    -B"$thisdir" \
    -static \
    -fuse-ld=musl-clang \
    -static-libgcc \
    -nostdinc \
    --sysroot "$libc" \
    -isystem "$libc_inc" \
    -l-user-start \
    $sflags \
    "$@" \
    $eflags \
    -L"$libc_lib" \
    -l-user-end
